SHOW DATABASES;

USE CHARSEARCH;

DESC SERIES;

DESC MOVIES;

SELECT * FROM SERIES;

SELECT * FROM MOVIES;

CREATE INDEX AA ON SERIES(NAME);

CREATE INDEX A ON SERIES(GENRE);

CREATE INDEX AA ON MOVIES(NAME);

CREATE INDEX A ON MOVIES(GENRE);

ALTER TABLE SERIES ADD IMDB DECIMAL(2,1);

ALTER TABLE MOVIES ADD IMDB DECIMAL(2,1);

ALTER TABLE SERIES MODIFY COLUMN NAME VARCHAR(150);

ALTER TABLE MOVIES MODIFY COLUMN NAME VARCHAR(150);

SELECT * FROM SERIES;

SELECT * FROM MOVIES;

SELECT * FROM SERIES WHERE NAME LIKE '%T_Y%';

INSERT INTO SERIES(IMDB,NAME) VALUES(9.5,'BREAKING BAD');

#SELECT * INSERT FROM

SELECT * FROM SERIES WHERE IMDB > 9.0;